version: '3.4'

services:
  baseify.api:
    image: ${DOCKER_REGISTRY-}baseifyapi
    build:
      context: .
      dockerfile: Baseify.Api/Dockerfile

  baseify-db:
    image: postgres:16.3
    container_name: Baseify.Db
    environment:
      - POSTGRES_DB=baseify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - bookify-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  baseify-idp:
    image: quay.io/keycloak/keycloak:25.0
    container_name: Baseify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - bookify-keycloack-data:/opt/keycloak/data
      - ./.files/keycloack/:/opt/keycloak/data/import/
    ports:
      - 18080:8080

  baseify-seq:
    image: datalust/seq:2024.3
    container_name: Baseify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  baseify-redis:
    image: redis:7.2.5
    container_name: Baseify.Redis
    restart: always
    ports:
      - '6379:6379'
  
volumes:
  bookify-db-data:
  bookify-keycloack-data:
